spring:
  application:
    name: User-Management-System
  
  profiles:
    active: prod  # CHANGED: was 'dev', now 'prod' for SQL Server

  # SQL SERVER CONFIGURATION - ADDED
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=TESTDB;encrypt=true;trustServerCertificate=true;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect  # CHANGED: was H2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect  # CHANGED: was H2Dialect

  h2:
    console:
      enabled: false  # CHANGED: was true, now false (disable H2)
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  web:
    resources:
      cache:
        period: 0

# Logging configuration - KEEP AS IS
logging:
  level:
    com.JavaSpring.Bank: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 10

# External API configuration - KEEP AS IS
external:
  api:
    jsonplaceholder:
      base-url: https://jsonplaceholder.typicode.com
      timeout: 5000

# Management endpoints - KEEP AS IS
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always